[gesture]
tap_timeout_ms = 200 # gesture is a tap if button held for less than this (ms)
movement_threshold = 100 # threshold before triggering directional gestures (px)

[gesture.commands]
tap         = "hyprctl dispatch togglespecialworkspace"
swipe_left  = "playerctl --player=spotify previous"
swipe_right = "playerctl --player=spotify next"
swipe_up    = "hyprctl dispatch workspace m-1"
swipe_down  = "hyprctl dispatch workspace m+1"

[scroll]
focus_poll_ms = 200 # how often to query hyprland for focused window (ms)

# app specific horizontal scroll rules
[[scroll.rules]]
window_class_regex    = "Spotify"
scroll_right_commands = ["wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"]
scroll_left_commands  = ["wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"]

[[scroll.rules]]
window_class_regex    = "firefox|chrome|chromium|zen"
scroll_right_commands = ["wtype -M ctrl -k Tab"]
scroll_left_commands  = ["wtype -M ctrl -M shift -k Tab"]